/*
 * Copyright © 2026 YuDongXing. All rights reserved.
 *
 * @author YuDongXing
 * @since 2026/05/10
 */

package top.yuxs.springbootdev.core.db.dialect;

import com.baomidou.mybatisplus.annotation.TableName;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import top.yuxs.springbootdev.core.db.annotation.ForeignKey;
import top.yuxs.springbootdev.core.db.annotation.Index;
import top.yuxs.springbootdev.core.db.enums.ForeignKeyAction;
import top.yuxs.springbootdev.core.db.enums.IndexType;
import top.yuxs.springbootdev.core.db.dialect.impl.H2Dialect;
import top.yuxs.springbootdev.core.db.dialect.impl.MysqlDialect;
import top.yuxs.springbootdev.core.db.dialect.impl.OracleDialect;
import top.yuxs.springbootdev.core.db.dialect.impl.PostgresqlDialect;
import top.yuxs.springbootdev.core.db.metadata.ColumnMetadata;
import top.yuxs.springbootdev.core.db.metadata.TableMetadata;

import java.util.Collections;

/**
 * 数据库方言组件单元测试
 */
class DialectTest {

    @TableName("ref_table")
    private static class ReferenceEntity {
    }

    @ForeignKey(name = "fk_test_ref", columns = "ref_id", referenceEntity = ReferenceEntity.class, referencedColumns = "id")
    private static class ForeignKeyHolder {
    }

    @ForeignKey(name = "fk_test_update", columns = "ref_id", referenceEntity = ReferenceEntity.class,
            referencedColumns = "id", onUpdate = ForeignKeyAction.CASCADE)
    private static class UnsupportedUpdateForeignKeyHolder {
    }

    @Test
    @DisplayName("测试 MySQL 方言标识符与类型映射")
    void testMysqlDialect() {
        MysqlDialect dialect = new MysqlDialect();
        Assertions.assertEquals("MYSQL", dialect.getDialectName());
        Assertions.assertEquals("`user`", dialect.quoteIdentifier("user"));
        Assertions.assertEquals("VARCHAR(64)", dialect.mapColumnType("VARCHAR(64)"));
        String mysqlModifyPrimaryKeySql = dialect.generateModifyColumnSql("sys_user",
                ColumnMetadata.builder().name("id").type("bigint").isPrimaryKey(true).build());
        Assertions.assertFalse(mysqlModifyPrimaryKeySql.contains("PRIMARY KEY"));

        TableMetadata table = TableMetadata.builder()
                .tableName("sys_user")
                .tableComment("用户表")
                .columns(Collections.singletonList(
                        ColumnMetadata.builder().name("id").type("BIGINT").isPrimaryKey(true).comment("主键").build()
                ))
                .indexes(Collections.emptyList())
                .foreignKeys(Collections.emptyList())
                .build();

        String sql = dialect.generateCreateTableSql(table);
        Assertions.assertTrue(sql.contains("CREATE TABLE `sys_user`"));
        Assertions.assertTrue(sql.contains("COMMENT='用户表'"));
        Assertions.assertFalse(sql.endsWith(";"));
    }

    @Test
    @DisplayName("测试 PostgreSQL 方言标识符与类型映射")
    void testPostgresqlDialect() {
        PostgresqlDialect dialect = new PostgresqlDialect();
        Assertions.assertEquals("POSTGRESQL", dialect.getDialectName());
        Assertions.assertEquals("\"user\"", dialect.quoteIdentifier("user"));
        Assertions.assertEquals("TIMESTAMP", dialect.mapColumnType("DATETIME"));
        Assertions.assertEquals("DOUBLE PRECISION", dialect.mapColumnType("DOUBLE"));
        Assertions.assertTrue(dialect.generateAddColumnSql("sys_user",
                ColumnMetadata.builder().name("sequence_id").type("bigint").isAutoIncrement(true).build())
                .contains("GENERATED BY DEFAULT AS IDENTITY"));

        TableMetadata table = TableMetadata.builder()
                .tableName("sys_user")
                .tableComment("用户表")
                .columns(Collections.singletonList(
                        ColumnMetadata.builder().name("create_time").type("DATETIME").comment("创建时间").build()
                ))
                .indexes(Collections.emptyList())
                .foreignKeys(Collections.emptyList())
                .build();

        String sql = dialect.generateCreateTableSql(table);
        Assertions.assertTrue(sql.contains("CREATE TABLE \"sys_user\""));
        Assertions.assertTrue(sql.contains("TIMESTAMP"));
        Assertions.assertFalse(sql.endsWith(";"));
        Assertions.assertEquals("ALTER TABLE \"sys_file\" ALTER COLUMN \"metadata\" TYPE TEXT USING \"metadata\"::TEXT",
                dialect.generateModifyColumnSql("sys_file",
                        ColumnMetadata.builder().name("metadata").type("text").build()));

        var comments = dialect.generateCommentSqls(table);
        Assertions.assertEquals(2, comments.size());
        Assertions.assertTrue(comments.get(0).contains("COMMENT ON TABLE \"sys_user\""));
    }

    @Test
    @DisplayName("测试 Oracle/DM 方言标识符与类型映射")
    void testOracleDialect() {
        OracleDialect dialect = new OracleDialect();
        Assertions.assertEquals("ORACLE", dialect.getDialectName());
        Assertions.assertEquals("\"USER\"", dialect.quoteIdentifier("user"));
        Assertions.assertEquals("TIMESTAMP", dialect.mapColumnType("DATETIME"));
        Assertions.assertEquals("NUMBER(20)", dialect.mapColumnType("BIGINT"));
        Assertions.assertEquals("CLOB", dialect.mapColumnType("JSON"));
        Assertions.assertEquals("VARCHAR2(255)", dialect.mapColumnType("VARCHAR2(255)"));
        Assertions.assertEquals("decimal(19,2)", dialect.normalizeColumnType("NUMBER(19,2)"));
        Assertions.assertEquals("timestamp", dialect.normalizeColumnType("TIMESTAMP(6)"));
        Assertions.assertTrue(dialect.generateAddColumnSql("sys_user",
                ColumnMetadata.builder().name("sequence_id").type("bigint").isAutoIncrement(true).build())
                .contains("GENERATED BY DEFAULT AS IDENTITY"));
        String modifyPrimaryKeySql = dialect.generateModifyColumnSql("sys_user",
                ColumnMetadata.builder().name("id").type("bigint").isPrimaryKey(true).build());
        Assertions.assertEquals("ALTER TABLE \"SYS_USER\" MODIFY (\"ID\" NUMBER(20))", modifyPrimaryKeySql);
        Assertions.assertFalse(modifyPrimaryKeySql.contains("PRIMARY KEY"));
        Assertions.assertTrue(dialect.getColumnsInfoSql().contains("c.CHAR_LENGTH"));
        Assertions.assertTrue(dialect.getColumnsInfoSql().contains("c.CHAR_USED = 'C'"));
        Assertions.assertTrue(dialect.generateColumnCommentSql("sys_user",
                ColumnMetadata.builder().name("username").comment("").build()).endsWith("IS ''"));
        var lobMigrationSqls = dialect.generateModifyColumnSqls("sys_file",
                ColumnMetadata.builder().name("metadata").type("text").build(),
                ColumnMetadata.builder().name("metadata").type("VARCHAR2(4000)").build());
        Assertions.assertEquals(4, lobMigrationSqls.size());
        Assertions.assertTrue(lobMigrationSqls.get(1).contains("TO_CLOB"));
        Assertions.assertTrue(lobMigrationSqls.get(3).contains("RENAME COLUMN"));
        Assertions.assertFalse(dialect.generateAddForeignKeySql("child_table",
                ForeignKeyHolder.class.getAnnotation(ForeignKey.class)).contains("ON DELETE RESTRICT"));
        Assertions.assertThrows(IllegalArgumentException.class, () -> dialect.generateAddForeignKeySql("child_table",
                UnsupportedUpdateForeignKeyHolder.class.getAnnotation(ForeignKey.class)));
    }

    @Test
    @DisplayName("测试 H2 方言标识符与类型映射")
    void testH2Dialect() {
        H2Dialect dialect = new H2Dialect();
        Assertions.assertEquals("H2", dialect.getDialectName());
        Assertions.assertEquals("`USER`", dialect.quoteIdentifier("user"));
        Assertions.assertEquals("TIMESTAMP", dialect.mapColumnType("DATETIME"));
        Assertions.assertEquals("VARCHAR(1000000000)", dialect.mapColumnType("TEXT"));
        Assertions.assertTrue(dialect.generateAddColumnSql("sys_user",
                ColumnMetadata.builder().name("sequence_id").type("bigint").isAutoIncrement(true).build())
                .contains("GENERATED BY DEFAULT AS IDENTITY"));
        Assertions.assertTrue(dialect.supportsColumnComments());
        Assertions.assertTrue(dialect.generateColumnCommentSql("sys_user",
                ColumnMetadata.builder().name("username").comment("用户名").build()).contains("COMMENT ON COLUMN"));

        Index uniqueIndex = UniqueIndexHolder.class.getAnnotation(Index.class);
        Assertions.assertTrue(dialect.generateCreateIndexSql("sys_user", uniqueIndex).startsWith("CREATE UNIQUE INDEX"));
        String foreignKeySql = dialect.generateAddForeignKeySql("child_table",
                ForeignKeyHolder.class.getAnnotation(ForeignKey.class));
        Assertions.assertTrue(foreignKeySql.contains("ON DELETE RESTRICT"));
        Assertions.assertTrue(foreignKeySql.contains("ON UPDATE RESTRICT"));
    }

    /**
     * 确保 H2 已有主键列修改类型时不会重复声明主键约束。
     */
    @Test
    @DisplayName("测试 H2 主键列类型修改 SQL 可实际执行")
    void shouldExecuteH2PrimaryKeyTypeChange() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:dialect_alter_test;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        H2Dialect dialect = new H2Dialect();

        jdbcTemplate.execute("CREATE TABLE DIALECT_ALTER_TEST (ID INT PRIMARY KEY)");
        String modifySql = dialect.generateModifyColumnSql("dialect_alter_test",
                ColumnMetadata.builder().name("id").type("bigint").isPrimaryKey(true).build());

        Assertions.assertFalse(modifySql.contains("PRIMARY KEY"));
        Assertions.assertDoesNotThrow(() -> jdbcTemplate.execute(modifySql));
    }

    /**
     * 确保 H2 能够保存自动 DDL 生成的表注释和列注释。
     */
    @Test
    @DisplayName("测试 H2 表和列注释可实际执行")
    void shouldExecuteH2Comments() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:dialect_comment_test;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        H2Dialect dialect = new H2Dialect();

        jdbcTemplate.execute("CREATE TABLE DIALECT_COMMENT_TEST (ID BIGINT PRIMARY KEY)");
        TableMetadata table = TableMetadata.builder()
                .tableName("dialect_comment_test")
                .tableComment("方言注释测试表")
                .columns(Collections.singletonList(
                        ColumnMetadata.builder().name("id").type("bigint").comment("主键").build()
                ))
                .indexes(Collections.emptyList())
                .foreignKeys(Collections.emptyList())
                .build();

        dialect.generateCommentSqls(table).forEach(jdbcTemplate::execute);
        String tableComment = jdbcTemplate.queryForObject(dialect.getTableCommentSql(), String.class,
                table.getTableName());
        Assertions.assertEquals("方言注释测试表", tableComment);
    }

    @Index(name = "uk_test_name", columns = "name", type = IndexType.UNIQUE)
    private static class UniqueIndexHolder {
    }

    @Test
    @DisplayName("测试所有方言生成的 JDBC SQL 不携带结尾分号")
    void testJdbcSqlDoesNotEndWithSemicolon() {
        TableMetadata table = TableMetadata.builder()
                .tableName("sys_user")
                .columns(Collections.singletonList(
                        ColumnMetadata.builder().name("id").type("BIGINT").isPrimaryKey(true).build()
                ))
                .indexes(Collections.emptyList())
                .foreignKeys(Collections.emptyList())
                .build();

        Assertions.assertFalse(new MysqlDialect().generateCreateTableSql(table).endsWith(";"));
        Assertions.assertFalse(new PostgresqlDialect().generateCreateTableSql(table).endsWith(";"));
        Assertions.assertFalse(new OracleDialect().generateCreateTableSql(table).endsWith(";"));
        Assertions.assertFalse(new H2Dialect().generateCreateTableSql(table).endsWith(";"));
    }
}
